name: Releases

on: push

jobs: 

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Main
        uses: actions/checkout@v3

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Aftman Toolchains
        run: aftman install

      - name: Create Packages Directory
        run: mkdir -p Packages

      - name: Run Stylua
        run: stylua src --check

      - name: Run Selene
        run : selene src

      - name: Build bridge-game.rbxm
        run: rojo build -o bridge-game.rbxl default.project.json

      - name: Upload bridge-game.rbxm as build artifact
        uses: actions/upload-artifact@v3
        with: 
          name: Bridge-Game
          path: bridge-game.rbxl